name: onde_gastei_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  args: ^2.0.0
  dotenv: ^3.0.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  jaguar_jwt: ^3.0.0
  logger: ^1.1.0
  mysql1: ^0.19.2
  shelf: ^1.2.0
  shelf_router: ^1.1.2

dev_dependencies:
  # lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
  strict: ^1.2.0
  shelf_router_generator: ^1.0.1
  build_runner: ^2.1.2
  injectable_generator: ^1.5.2
  mocktail: ^0.1.4
