name: onde_gastei_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  args: ^2.3.1
  dotenv: ^4.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  jaguar_jwt: ^3.0.0
  logger: ^1.1.0
  mysql1: ^0.19.2
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  crypto: ^3.0.2

dev_dependencies:
  # lints: ^1.0.0
  test_process: ^2.0.2
  test: ^1.21.1
  strict: ^1.4.0
  shelf_router_generator: ^1.0.2
  build_runner: ^2.1.10
  injectable_generator: ^1.5.3
  mocktail: ^0.3.0
