name: CI/CD Swarm

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Extract version from pubspec
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d+ -f1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version detected: $VERSION"

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ondegastei-api:${VERSION} .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ondegastei-api:${VERSION}

      - name: Deploy Swarm
        run: |
          docker stack deploy \
            -c docker-stack.yml \
            stack_api
